package com.jervisffb.engine.rules.bb2020.serialize

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 *
 * BB2020 subclass registrations for polymorphic bases defined in
 * `rules.common.*`. Composed with [coreSerializerModule] and
 * [bb2025SerializerModule] at boot in [JervisSerialization].
 */
val bb2020SerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.rules.common.tables.ArgueTheCallTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020ArgueTheCallTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020CasualtyTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StuntyInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7StuntyInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardKickOffEventTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7KickOffEventTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020LastingInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardPrayersToNuffleTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7PrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.RangeRuler::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020RangeRuler::class)
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.rules.BB72020Rules::class, com.jervisffb.engine.rules.BB72020RulesSerializer)
        subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class, com.jervisffb.engine.rules.FumbblBB2020RulesSerializer)
        subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class, com.jervisffb.engine.rules.StandardBB2020RulesSerializer)
    }
    polymorphic(com.jervisffb.engine.rules.common.skills.SkillSettings::class) {
        subclass(com.jervisffb.engine.rules.bb2020.BB2020SkillSettings::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.TeamActions::class) {
        subclass(com.jervisffb.engine.rules.bb2020.BB2020TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.WeatherTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.AutumnWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.SpringWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.SummerWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.WinterWeatherTable::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizards.Wizard::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.HirelingSportsWizard::class)
    }
}
