package com.jervisffb.ui.game.state

import com.jervisffb.engine.ActionRequest
import com.jervisffb.engine.GameEngineController
import com.jervisffb.engine.GameSettings
import com.jervisffb.engine.actions.DiceFaces
import com.jervisffb.engine.actions.GameAction
import com.jervisffb.engine.actions.RollDice
import com.jervisffb.engine.utils.containsActionWithRandomBehavior
import com.jervisffb.engine.utils.createRandomAction
import com.jervisffb.ui.game.viewmodel.MenuViewModel
import com.jervisffb.ui.menu.TeamActionMode

/**
 * Action provider used during challenges. Random actions are generated by the provider so the
 * client can still display them while the coach cannot choose their results.
 */
class ChallengeActionProvider(
    game: GameEngineController,
    menuViewModel: MenuViewModel,
    clientMode: TeamActionMode,
    gameSettings: GameSettings,
) : ManualActionProvider(game, menuViewModel, clientMode, gameSettings) {

    override fun calculateAutomaticResponse(actions: ActionRequest): GameAction? {
        super.calculateAutomaticResponse(actions)?.let { return it }

        // ManualActionProvider deliberately leaves client-owned random actions to the UI.
        // Challenges still use client-owned rolls for their presentation, but the random result
        // itself must be generated automatically so the coach cannot choose it.
        if (game.lastActionWasUndo()) return null
        return if (actions.containsActionWithRandomBehavior() && actions.hasConstrainedDiceRoll()) {
            createRandomAction(game)
        } else {
            null
        }
    }

    /**
     * A constrained dice request is the engine-level signal that a challenge
     * rule has changed the random result space. The provider generates those
     * results; non-restricted dice rolls remain selectable by the coach.
     *
     * TODO Is there a better way to detect this that doesn't rely on a heuristic?
     */
    private fun ActionRequest.hasConstrainedDiceRoll(): Boolean {
        return filterIsInstance<RollDice>().any { request ->
            request.dice.indices.any { index ->
                request.getAllowedFaces(index) != DiceFaces.all(request.dice[index])
            }
        }
    }
}
