package com.jervisffb.engine.serialization

import com.jervisffb.engine.challenge.ChallengeScore
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 *
 * Polymorphic subclass registrations for types whose entire class hierarchy
 * lives in `engine.*` or `rules.common.*` — no ruleset-specific subclasses.
 * Ruleset-specific subclasses (BB2020 / BB2025) are registered in
 * `bb2020Serializers.kt` / `bb2025Serializers.kt` and combined at boot in
 * [JervisSerialization].
 */
val coreSerializerModule = SerializersModule {
    polymorphic(ChallengeScore::class) {
        subclass(com.jervisffb.engine.challenge.ChallengeScore.CompletionOnly::class)
        subclass(com.jervisffb.engine.challenge.ChallengeScore.ProbabilityScore::class)
    }
    polymorphic(com.jervisffb.engine.rules.builder.BallSelectorRule::class) {
        subclass(com.jervisffb.engine.rules.builder.RollOnUnusualBallTable::class)
        subclass(com.jervisffb.engine.rules.builder.SpecificUnusualBall::class)
        subclass(com.jervisffb.engine.rules.builder.StandardBall::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.BiasedReferee::class) {
        subclass(com.jervisffb.engine.model.inducements.StandardBiasedReferee::class)
        subclass(com.jervisffb.engine.model.inducements.DodgyLeagueRep::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.procedures.DieRoll::class) {
        subclass(com.jervisffb.engine.rules.common.procedures.BlockDieRoll::class)
        subclass(com.jervisffb.engine.rules.common.procedures.D3DieRoll::class)
        subclass(com.jervisffb.engine.rules.common.procedures.D6DieRoll::class)
    }
    polymorphic(com.jervisffb.engine.actions.GameAction::class) {
        subclass(com.jervisffb.engine.actions.AddPlayerKeyword::class)
        subclass(com.jervisffb.engine.actions.AddPlayerSkill::class)
        subclass(com.jervisffb.engine.actions.BlockTypeSelected::class)
        subclass(com.jervisffb.engine.actions.Cancel::class)
        subclass(com.jervisffb.engine.actions.ChangePlayerBaseStat::class)
        subclass(com.jervisffb.engine.actions.CoinSideSelected::class)
        subclass(com.jervisffb.engine.actions.CoinTossResult::class)
        subclass(com.jervisffb.engine.actions.CompositeGameAction::class)
        subclass(com.jervisffb.engine.actions.Confirm::class)
        subclass(com.jervisffb.engine.actions.Continue::class)
        subclass(com.jervisffb.engine.actions.D12Result::class)
        subclass(com.jervisffb.engine.actions.D16Result::class)
        subclass(com.jervisffb.engine.actions.D20Result::class)
        subclass(com.jervisffb.engine.actions.D2Result::class)
        subclass(com.jervisffb.engine.actions.D3Result::class)
        subclass(com.jervisffb.engine.actions.D4Result::class)
        subclass(com.jervisffb.engine.actions.D6Result::class)
        subclass(com.jervisffb.engine.actions.D8Result::class)
        subclass(com.jervisffb.engine.actions.DBlockResult::class)
        subclass(com.jervisffb.engine.actions.DicePoolResultsSelected::class)
        subclass(com.jervisffb.engine.actions.DiceRollResults::class)
        subclass(com.jervisffb.engine.actions.DirectionSelected::class)
        subclass(com.jervisffb.engine.actions.DogoutSelected::class)
        subclass(com.jervisffb.engine.actions.EndAction::class)
        subclass(com.jervisffb.engine.actions.EndSetup::class)
        subclass(com.jervisffb.engine.actions.EndTurn::class)
        subclass(com.jervisffb.engine.actions.ForegoActivationSelected::class)
        subclass(com.jervisffb.engine.actions.InducementsSelected::class)
        subclass(com.jervisffb.engine.actions.MoveTypeSelected::class)
        subclass(com.jervisffb.engine.actions.NoRerollSelected::class)
        subclass(com.jervisffb.engine.actions.PassTypeSelected::class)
        subclass(com.jervisffb.engine.actions.PitchSquareSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerActionSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerDeselected::class)
        subclass(com.jervisffb.engine.actions.PlayerSelected::class)
        subclass(com.jervisffb.engine.actions.PlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RandomPlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RemovePlayerKeyword::class)
        subclass(com.jervisffb.engine.actions.RemovePlayerSkill::class)
        subclass(com.jervisffb.engine.actions.RerollOptionSelected::class)
        subclass(com.jervisffb.engine.actions.Revert::class)
        subclass(com.jervisffb.engine.actions.SetBallState::class)
        subclass(com.jervisffb.engine.actions.MovePlayer::class)
        subclass(com.jervisffb.engine.actions.SetPlayerState::class)
        subclass(com.jervisffb.engine.actions.SkillSelected::class)
        subclass(com.jervisffb.engine.actions.Undo::class)
        polymorphic(com.jervisffb.engine.actions.DevModeGameAction::class) {
            subclass(com.jervisffb.engine.actions.AddPlayerKeyword::class)
            subclass(com.jervisffb.engine.actions.AddPlayerSkill::class)
            subclass(com.jervisffb.engine.actions.ChangePlayerBaseStat::class)
            subclass(com.jervisffb.engine.actions.RemovePlayerKeyword::class)
            subclass(com.jervisffb.engine.actions.RemovePlayerSkill::class)
            subclass(com.jervisffb.engine.actions.SetBallState::class)
            subclass(com.jervisffb.engine.actions.MovePlayer::class)
            subclass(com.jervisffb.engine.actions.SetPlayerState::class)
        }
        polymorphic(com.jervisffb.engine.actions.DieResult::class) {
            subclass(com.jervisffb.engine.actions.D12Result::class)
            subclass(com.jervisffb.engine.actions.D16Result::class)
            subclass(com.jervisffb.engine.actions.D20Result::class)
            subclass(com.jervisffb.engine.actions.D2Result::class)
            subclass(com.jervisffb.engine.actions.D3Result::class)
            subclass(com.jervisffb.engine.actions.D4Result::class)
            subclass(com.jervisffb.engine.actions.D6Result::class)
            subclass(com.jervisffb.engine.actions.D8Result::class)
            subclass(com.jervisffb.engine.actions.DBlockResult::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.Inducement::class) {
        subclass(com.jervisffb.engine.model.inducements.settings.BiasedRefereeInducement::class)
        subclass(com.jervisffb.engine.model.inducements.settings.BiasedRefereesInducementList::class)
        subclass(com.jervisffb.engine.model.inducements.settings.ExpandedMercenaryInducements::class)
        subclass(com.jervisffb.engine.model.inducements.settings.InfamousCoachingStaffInducement::class)
        subclass(com.jervisffb.engine.model.inducements.settings.InfamousCoachingStaffsInducementList::class)
        subclass(com.jervisffb.engine.model.inducements.settings.SimpleInducement::class)
        subclass(com.jervisffb.engine.model.inducements.settings.StandardMercenaryInducement::class)
        subclass(com.jervisffb.engine.model.inducements.settings.StarPlayerInducement::class)
        subclass(com.jervisffb.engine.model.inducements.settings.StarPlayersInducementList::class)
        subclass(com.jervisffb.engine.model.inducements.settings.WizardInducement::class)
        subclass(com.jervisffb.engine.model.inducements.settings.WizardsInducementList::class)
        polymorphic(com.jervisffb.engine.model.inducements.settings.InducementGroup::class) {
            subclass(com.jervisffb.engine.model.inducements.settings.BiasedRefereesInducementList::class)
            subclass(com.jervisffb.engine.model.inducements.settings.InfamousCoachingStaffsInducementList::class)
            subclass(com.jervisffb.engine.model.inducements.settings.StarPlayersInducementList::class)
            subclass(com.jervisffb.engine.model.inducements.settings.WizardsInducementList::class)
        }
        polymorphic(com.jervisffb.engine.model.inducements.settings.SingleInducement::class) {
            subclass(com.jervisffb.engine.model.inducements.settings.BiasedRefereeInducement::class)
            subclass(com.jervisffb.engine.model.inducements.settings.ExpandedMercenaryInducements::class)
            subclass(com.jervisffb.engine.model.inducements.settings.InfamousCoachingStaffInducement::class)
            subclass(com.jervisffb.engine.model.inducements.settings.SimpleInducement::class)
            subclass(com.jervisffb.engine.model.inducements.settings.StandardMercenaryInducement::class)
            subclass(com.jervisffb.engine.model.inducements.settings.StarPlayerInducement::class)
            subclass(com.jervisffb.engine.model.inducements.settings.WizardInducement::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.InfamousCoachingStaff::class) {
        subclass(com.jervisffb.engine.model.inducements.JosefBugman::class)
        subclass(com.jervisffb.engine.model.inducements.KariColdsteel::class)
        subclass(com.jervisffb.engine.model.inducements.PapaSkullbones::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Position::class) {
        subclass(com.jervisffb.engine.rules.common.roster.RosterPosition::class)
        subclass(com.jervisffb.engine.rules.common.roster.StarPlayerPosition::class)
    }
    polymorphic(com.jervisffb.engine.serialization.SerializedPlayer::class) {
    }
    polymorphic(com.jervisffb.engine.serialization.SerializedTeam::class) {
    }
    polymorphic(com.jervisffb.engine.rules.builder.StadiumRule::class) {
        subclass(com.jervisffb.engine.rules.builder.NoStadium::class)
        subclass(com.jervisffb.engine.rules.builder.RollForStadiumUsed::class)
        subclass(com.jervisffb.engine.rules.builder.SpecificStadium::class)
    }
}
