package com.jervisffb.engine.serialization

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/** Generated by :tools:generateSerializers. DO NOT MODIFY! */
val coreSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.actions.GameAction::class) {
        subclass(com.jervisffb.engine.actions.AddPlayerKeyword::class)
        subclass(com.jervisffb.engine.actions.AddPlayerSkill::class)
        subclass(com.jervisffb.engine.actions.BlockTypeSelected::class)
        subclass(com.jervisffb.engine.actions.Cancel::class)
        subclass(com.jervisffb.engine.actions.ChangePlayerBaseStat::class)
        subclass(com.jervisffb.engine.actions.CoinSideSelected::class)
        subclass(com.jervisffb.engine.actions.CoinTossResult::class)
        subclass(com.jervisffb.engine.actions.CompositeGameAction::class)
        subclass(com.jervisffb.engine.actions.Confirm::class)
        subclass(com.jervisffb.engine.actions.Continue::class)
        subclass(com.jervisffb.engine.actions.D12Result::class)
        subclass(com.jervisffb.engine.actions.D16Result::class)
        subclass(com.jervisffb.engine.actions.D20Result::class)
        subclass(com.jervisffb.engine.actions.D2Result::class)
        subclass(com.jervisffb.engine.actions.D3Result::class)
        subclass(com.jervisffb.engine.actions.D4Result::class)
        subclass(com.jervisffb.engine.actions.D6Result::class)
        subclass(com.jervisffb.engine.actions.D8Result::class)
        subclass(com.jervisffb.engine.actions.DBlockResult::class)
        subclass(com.jervisffb.engine.actions.DicePoolResultsSelected::class)
        subclass(com.jervisffb.engine.actions.DiceRollResults::class)
        subclass(com.jervisffb.engine.actions.DirectionSelected::class)
        subclass(com.jervisffb.engine.actions.DogoutSelected::class)
        subclass(com.jervisffb.engine.actions.EndAction::class)
        subclass(com.jervisffb.engine.actions.EndSetup::class)
        subclass(com.jervisffb.engine.actions.EndTurn::class)
        subclass(com.jervisffb.engine.actions.ForegoActivationSelected::class)
        subclass(com.jervisffb.engine.actions.InducementEffectSelected::class)
        subclass(com.jervisffb.engine.actions.InducementsSelected::class)
        subclass(com.jervisffb.engine.actions.MovePlayer::class)
        subclass(com.jervisffb.engine.actions.MoveTypeSelected::class)
        subclass(com.jervisffb.engine.actions.NoRerollSelected::class)
        subclass(com.jervisffb.engine.actions.PassTypeSelected::class)
        subclass(com.jervisffb.engine.actions.PitchSquareSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerActionSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerDeselected::class)
        subclass(com.jervisffb.engine.actions.PlayerSelected::class)
        subclass(com.jervisffb.engine.actions.PlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RandomPlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RemovePlayerKeyword::class)
        subclass(com.jervisffb.engine.actions.RemovePlayerSkill::class)
        subclass(com.jervisffb.engine.actions.RerollOptionSelected::class)
        subclass(com.jervisffb.engine.actions.Revert::class)
        subclass(com.jervisffb.engine.actions.SetBallState::class)
        subclass(com.jervisffb.engine.actions.SetPlayerState::class)
        subclass(com.jervisffb.engine.actions.SkillSelected::class)
        subclass(com.jervisffb.engine.actions.Undo::class)
        polymorphic(com.jervisffb.engine.actions.AdminGameAction::class) {
            subclass(com.jervisffb.engine.actions.AddPlayerKeyword::class)
            subclass(com.jervisffb.engine.actions.AddPlayerSkill::class)
            subclass(com.jervisffb.engine.actions.ChangePlayerBaseStat::class)
            subclass(com.jervisffb.engine.actions.MovePlayer::class)
            subclass(com.jervisffb.engine.actions.RemovePlayerKeyword::class)
            subclass(com.jervisffb.engine.actions.RemovePlayerSkill::class)
            subclass(com.jervisffb.engine.actions.SetBallState::class)
            subclass(com.jervisffb.engine.actions.SetPlayerState::class)
        }
        polymorphic(com.jervisffb.engine.actions.DieResult::class) {
            subclass(com.jervisffb.engine.actions.D12Result::class)
            subclass(com.jervisffb.engine.actions.D16Result::class)
            subclass(com.jervisffb.engine.actions.D20Result::class)
            subclass(com.jervisffb.engine.actions.D2Result::class)
            subclass(com.jervisffb.engine.actions.D3Result::class)
            subclass(com.jervisffb.engine.actions.D4Result::class)
            subclass(com.jervisffb.engine.actions.D6Result::class)
            subclass(com.jervisffb.engine.actions.D8Result::class)
            subclass(com.jervisffb.engine.actions.DBlockResult::class)
        }
    }
    polymorphic(com.jervisffb.engine.challenge.ChallengeScore::class) {
        subclass(com.jervisffb.engine.challenge.ChallengeScore.CompletionOnly::class)
        subclass(com.jervisffb.engine.challenge.ChallengeScore.ProbabilityScore::class)
    }
    polymorphic(com.jervisffb.engine.model.PlayerState::class) {
        subclass(com.jervisffb.engine.model.PlayerDogoutState::class)
        subclass(com.jervisffb.engine.model.PlayerPitchState::class)
    }
    polymorphic(com.jervisffb.engine.model.SkillValue::class) {
        subclass(com.jervisffb.engine.model.SkillValue.IntAdjustment::class)
        subclass(com.jervisffb.engine.model.SkillValue.IntTarget::class)
        subclass(com.jervisffb.engine.model.SkillValue.Keyword::class)
        subclass(com.jervisffb.engine.model.SkillValue.None::class)
    }
    polymorphic(com.jervisffb.engine.model.locations.Location::class) {
        subclass(com.jervisffb.engine.model.locations.Dogout::class)
        subclass(com.jervisffb.engine.model.locations.GiantLocation::class)
        subclass(com.jervisffb.engine.model.locations.PitchCoordinateImpl::class)
        polymorphic(com.jervisffb.engine.model.locations.OnPitchLocation::class) {
            subclass(com.jervisffb.engine.model.locations.GiantLocation::class)
            subclass(com.jervisffb.engine.model.locations.PitchCoordinateImpl::class)
            polymorphic(com.jervisffb.engine.model.locations.PitchCoordinate::class) {
                subclass(com.jervisffb.engine.model.locations.PitchCoordinateImpl::class)
            }
        }
        polymorphic(com.jervisffb.engine.model.locations.PitchCoordinate::class) {
            subclass(com.jervisffb.engine.model.locations.PitchCoordinateImpl::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.modifiers.PlayerStatusEffect::class) {
        subclass(com.jervisffb.engine.model.modifiers.OwnedPlayerStatusEffect::class)
        subclass(com.jervisffb.engine.model.modifiers.SimplePlayerStatusEffect::class)
    }
    polymorphic(com.jervisffb.engine.rules.builder.BallSelectorRule::class) {
        subclass(com.jervisffb.engine.rules.builder.RollOnUnusualBallTable::class)
        subclass(com.jervisffb.engine.rules.builder.SpecificUnusualBall::class)
        subclass(com.jervisffb.engine.rules.builder.StandardBall::class)
    }
    polymorphic(com.jervisffb.engine.rules.builder.StadiumRule::class) {
        subclass(com.jervisffb.engine.rules.builder.NoStadium::class)
        subclass(com.jervisffb.engine.rules.builder.RollForStadiumUsed::class)
        subclass(com.jervisffb.engine.rules.builder.SpecificStadium::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.ActionType::class) {
        subclass(com.jervisffb.engine.rules.common.actions.PlayerSpecialActionType::class)
        subclass(com.jervisffb.engine.rules.common.actions.PlayerStandardActionType::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.procedures.DieRoll::class) {
        subclass(com.jervisffb.engine.rules.common.procedures.BlockDieRoll::class)
        subclass(com.jervisffb.engine.rules.common.procedures.D3DieRoll::class)
        subclass(com.jervisffb.engine.rules.common.procedures.D6DieRoll::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Position::class) {
        subclass(com.jervisffb.engine.rules.common.roster.RosterPosition::class)
        subclass(com.jervisffb.engine.rules.common.roster.StarPlayerPosition::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.SpecialRules::class) {
        subclass(com.jervisffb.engine.rules.common.roster.PlayerSpecialRule::class)
        subclass(com.jervisffb.engine.rules.common.roster.RegionalSpecialRule::class)
        subclass(com.jervisffb.engine.rules.common.roster.TeamSpecialRule::class)
    }
    polymorphic(com.jervisffb.engine.sprites.SpriteSource::class) {
        subclass(com.jervisffb.engine.sprites.SingleSprite::class)
        subclass(com.jervisffb.engine.sprites.SpriteSheet::class)
    }
    polymorphic(com.jervisffb.engine.statistics.probability.scorer.ProbabilityScoreResult::class) {
        subclass(com.jervisffb.engine.statistics.probability.scorer.ProbabilityScoreResult.Scored::class)
        subclass(com.jervisffb.engine.statistics.probability.scorer.ProbabilityScoreResult.Unsupported::class)
    }
}
