package com.jervisffb.engine.bb2020.serialization

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/** Generated by :tools:generateSerializers. DO NOT MODIFY! */
val bb2020SerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.common.AbstractRules::class) {
        subclass(com.jervisffb.engine.bb2020.BB72020Rules::class, com.jervisffb.engine.bb2020.BB72020RulesSerializer)
        subclass(com.jervisffb.engine.bb2020.FumbblBB2020Rules::class, com.jervisffb.engine.bb2020.FumbblBB2020RulesSerializer)
        subclass(com.jervisffb.engine.bb2020.StandardBB2020Rules::class, com.jervisffb.engine.bb2020.StandardBB2020RulesSerializer)
    }
    polymorphic(com.jervisffb.engine.model.inducements.InducementEffect::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.effects.AssassinationAttempt::class)
        subclass(com.jervisffb.engine.bb2020.inducements.effects.SpotTheSneak::class)
        subclass(com.jervisffb.engine.bb2020.inducements.infamouscoach.ByThePowerOfTheGoods::class)
        polymorphic(com.jervisffb.engine.bb2020.inducements.effects.DirtyTrick::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.effects.SpotTheSneak::class)
        }
        polymorphic(com.jervisffb.engine.bb2020.inducements.effects.MiscellaneousMayhem::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.effects.AssassinationAttempt::class)
        }
        polymorphic(com.jervisffb.engine.model.inducements.card.SpecialPlayCard::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.effects.AssassinationAttempt::class)
            subclass(com.jervisffb.engine.bb2020.inducements.effects.SpotTheSneak::class)
            polymorphic(com.jervisffb.engine.bb2020.inducements.effects.DirtyTrick::class) {
                subclass(com.jervisffb.engine.bb2020.inducements.effects.SpotTheSneak::class)
            }
            polymorphic(com.jervisffb.engine.bb2020.inducements.effects.MiscellaneousMayhem::class) {
                subclass(com.jervisffb.engine.bb2020.inducements.effects.AssassinationAttempt::class)
            }
        }
        polymorphic(com.jervisffb.engine.model.inducements.infamouscoach.InfamousCoachAbility::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.infamouscoach.ByThePowerOfTheGoods::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.biasedreferee.BiasedReferee::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.biasedreferee.JormTheOgre::class)
        subclass(com.jervisffb.engine.bb2020.inducements.biasedreferee.RanulfRedHokuli::class)
        subclass(com.jervisffb.engine.bb2020.inducements.biasedreferee.StandardBiasedReferee::class)
        subclass(com.jervisffb.engine.bb2020.inducements.biasedreferee.TheThrundlefootTriplets::class)
        subclass(com.jervisffb.engine.bb2020.inducements.biasedreferee.ThoronKorensson::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.card.SpecialPlayCard::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.effects.AssassinationAttempt::class)
        subclass(com.jervisffb.engine.bb2020.inducements.effects.SpotTheSneak::class)
        polymorphic(com.jervisffb.engine.bb2020.inducements.effects.DirtyTrick::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.effects.SpotTheSneak::class)
        }
        polymorphic(com.jervisffb.engine.bb2020.inducements.effects.MiscellaneousMayhem::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.effects.AssassinationAttempt::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.infamouscoach.InfamousCoachingStaff::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.infamouscoach.JosefBugman::class)
        subclass(com.jervisffb.engine.bb2020.inducements.infamouscoach.KariColdsteel::class)
        subclass(com.jervisffb.engine.bb2020.inducements.infamouscoach.PapaSkullbones::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.Inducement::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.ExpandedMercenaryInducements::class)
        polymorphic(com.jervisffb.engine.model.inducements.settings.TeamPlayerInducement::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.ExpandedMercenaryInducements::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.InducementType::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.BB2020InducementType::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.TeamPlayerInducement::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.ExpandedMercenaryInducements::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizard.Wizard::class) {
        subclass(com.jervisffb.engine.bb2020.inducements.wizards.HirelingSportsWizard::class)
        polymorphic(com.jervisffb.engine.bb2020.inducements.wizards.BB2020Wizard::class) {
            subclass(com.jervisffb.engine.bb2020.inducements.wizards.HirelingSportsWizard::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.bb2020.BB72020Rules::class, com.jervisffb.engine.bb2020.BB72020RulesSerializer)
        subclass(com.jervisffb.engine.bb2020.FumbblBB2020Rules::class, com.jervisffb.engine.bb2020.FumbblBB2020RulesSerializer)
        subclass(com.jervisffb.engine.bb2020.StandardBB2020Rules::class, com.jervisffb.engine.bb2020.StandardBB2020RulesSerializer)
        polymorphic(com.jervisffb.engine.common.AbstractRules::class) {
            subclass(com.jervisffb.engine.bb2020.BB72020Rules::class, com.jervisffb.engine.bb2020.BB72020RulesSerializer)
            subclass(com.jervisffb.engine.bb2020.FumbblBB2020Rules::class, com.jervisffb.engine.bb2020.FumbblBB2020RulesSerializer)
            subclass(com.jervisffb.engine.bb2020.StandardBB2020Rules::class, com.jervisffb.engine.bb2020.StandardBB2020RulesSerializer)
        }
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.TeamActions::class) {
        subclass(com.jervisffb.engine.bb2020.BB2020TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.skills.SkillSettings::class) {
        subclass(com.jervisffb.engine.bb2020.BB2020SkillSettings::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.ArgueTheCallTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020ArgueTheCallTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020CasualtyTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.DesperateMeasuresTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB7DesperateMeasuresTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020StandardInjuryTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.BB2020StuntyInjuryTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.BB7StandardInjuryTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.BB7StuntyInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020StandardKickOffEventTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.BB7KickOffEventTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020LastingInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020StandardPrayersToNuffleTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.BB7PrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.RangeRuler::class) {
        subclass(com.jervisffb.engine.bb2020.tables.BB2020RangeRuler::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.WeatherTable::class) {
        subclass(com.jervisffb.engine.bb2020.tables.AutumnWeatherTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.BB2020StandardWeatherTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.SpringWeatherTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.SummerWeatherTable::class)
        subclass(com.jervisffb.engine.bb2020.tables.WinterWeatherTable::class)
    }
}
