package com.jervisffb.engine.bb2020.serialization

import com.jervisffb.engine.bb2020.BB2020SkillSettings
import com.jervisffb.engine.bb2020.BB2020TeamActions
import com.jervisffb.engine.bb2020.BB72020Rules
import com.jervisffb.engine.bb2020.BB72020RulesSerializer
import com.jervisffb.engine.bb2020.FumbblBB2020Rules
import com.jervisffb.engine.bb2020.FumbblBB2020RulesSerializer
import com.jervisffb.engine.bb2020.StandardBB2020Rules
import com.jervisffb.engine.bb2020.StandardBB2020RulesSerializer
import com.jervisffb.engine.bb2020.inducements.wizards.HirelingSportsWizard
import com.jervisffb.engine.bb2020.tables.AutumnWeatherTable
import com.jervisffb.engine.bb2020.tables.BB2020ArgueTheCallTable
import com.jervisffb.engine.bb2020.tables.BB2020CasualtyTable
import com.jervisffb.engine.bb2020.tables.BB2020LastingInjuryTable
import com.jervisffb.engine.bb2020.tables.BB2020RangeRuler
import com.jervisffb.engine.bb2020.tables.BB2020StandardInjuryTable
import com.jervisffb.engine.bb2020.tables.BB2020StandardKickOffEventTable
import com.jervisffb.engine.bb2020.tables.BB2020StandardPrayersToNuffleTable
import com.jervisffb.engine.bb2020.tables.BB2020StandardWeatherTable
import com.jervisffb.engine.bb2020.tables.BB2020StuntyInjuryTable
import com.jervisffb.engine.bb2020.tables.BB7KickOffEventTable
import com.jervisffb.engine.bb2020.tables.BB7PrayersToNuffleTable
import com.jervisffb.engine.bb2020.tables.BB7StandardInjuryTable
import com.jervisffb.engine.bb2020.tables.BB7StuntyInjuryTable
import com.jervisffb.engine.bb2020.tables.SpringWeatherTable
import com.jervisffb.engine.bb2020.tables.SummerWeatherTable
import com.jervisffb.engine.bb2020.tables.WinterWeatherTable
import com.jervisffb.engine.model.inducements.wizards.Wizard
import com.jervisffb.engine.rules.Rules
import com.jervisffb.engine.rules.common.actions.TeamActions
import com.jervisffb.engine.rules.common.skills.SkillSettings
import com.jervisffb.engine.rules.common.tables.ArgueTheCallTable
import com.jervisffb.engine.rules.common.tables.CasualtyTable
import com.jervisffb.engine.rules.common.tables.InjuryTable
import com.jervisffb.engine.rules.common.tables.KickOffTable
import com.jervisffb.engine.rules.common.tables.LastingInjuryTable
import com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable
import com.jervisffb.engine.rules.common.tables.RangeRuler
import com.jervisffb.engine.rules.common.tables.WeatherTable
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 *
 * BB2020 subclass registrations for polymorphic bases defined in
 * `rules.common.*`. Composed with [coreSerializerModule] and
 * [bb2025SerializerModule] at boot in [JervisSerialization].
 */
val bb2020SerializerModule = SerializersModule {
    polymorphic(ArgueTheCallTable::class) {
        subclass(BB2020ArgueTheCallTable::class)
    }
    polymorphic(CasualtyTable::class) {
        subclass(BB2020CasualtyTable::class)
    }
    polymorphic(InjuryTable::class) {
        subclass(BB2020StandardInjuryTable::class)
        subclass(BB2020StuntyInjuryTable::class)
        subclass(BB7StandardInjuryTable::class)
        subclass(BB7StuntyInjuryTable::class)
    }
    polymorphic(KickOffTable::class) {
        subclass(BB2020StandardKickOffEventTable::class)
        subclass(BB7KickOffEventTable::class)
    }
    polymorphic(LastingInjuryTable::class) {
        subclass(BB2020LastingInjuryTable::class)
    }
    polymorphic(PrayersToNuffleTable::class) {
        subclass(BB2020StandardPrayersToNuffleTable::class)
        subclass(BB7PrayersToNuffleTable::class)
    }
    polymorphic(RangeRuler::class) {
        subclass(BB2020RangeRuler::class)
    }
    polymorphic(Rules::class) {
        subclass(BB72020Rules::class, BB72020RulesSerializer)
        subclass(FumbblBB2020Rules::class, FumbblBB2020RulesSerializer)
        subclass(StandardBB2020Rules::class, StandardBB2020RulesSerializer)
    }
    polymorphic(SkillSettings::class) {
        subclass(BB2020SkillSettings::class)
    }
    polymorphic(TeamActions::class) {
        subclass(BB2020TeamActions::class)
    }
    polymorphic(WeatherTable::class) {
        subclass(AutumnWeatherTable::class)
        subclass(BB2020StandardWeatherTable::class)
        subclass(SpringWeatherTable::class)
        subclass(SummerWeatherTable::class)
        subclass(WinterWeatherTable::class)
    }
    polymorphic(Wizard::class) {
        subclass(HirelingSportsWizard::class)
    }
}
