package com.jervisffb.fumbbl.net.model

import com.jervisffb.fumbbl.net.api.serialization.FumbblEnum
import com.jervisffb.fumbbl.net.api.serialization.FumbblEnumSerializer
import kotlinx.serialization.Serializable

class DialogIdSerializer : FumbblEnumSerializer<com.jervisffb.fumbbl.net.model.DialogId>(com.jervisffb.fumbbl.net.model.DialogId::class)

@Serializable(with = com.jervisffb.fumbbl.net.model.DialogIdSerializer::class)
enum class DialogId(override val id: String) : FumbblEnum {
    ABOUT("about"),
    APOTHECARY_CHOICE("apothecaryChoice"),
    ARGUE_THE_CALL("argueTheCall"),
    BLOCK_ROLL("blockRoll"),
    BLOCK_ROLL_PARTIAL_RE_ROLL("blockRollPartialReRoll"),
    BRIBERY_AND_CORRUPTION_RE_ROLL("briberyAndCorruptionReRoll"),
    BRIBES("bribes"),
    BUY_CARDS("buyCards"),
    BUY_CARDS_AND_INDUCEMENTS("buyCardsAndInducements"),
    BUY_INDUCEMENTS("buyInducements"),
    CHANGE_LIST("changeList"),
    CHAT_COMMANDS("chatCommands"),
    COIN_CHOICE("coinChoice"),
    CONCEDE_GAME("concedeGame"),
    CONFIRM_END_ACTION("confirmEndAction"),
    DEFENDER_ACTION("defenderAction"),
    END_TURN("endTurn"),
    FOLLOWUP_CHOICE("followupChoice"),
    GAME_CHOICE("gameChoice"),
    GAME_COACH_PASSWORD("gameCoachPassword"),
    GAME_STATISTICS("gameStatistics"),
    INFORMATION("information"),
    INFORMATION_OKAY("informationOkay"),
    INTERCEPTION("interception"),
    INVALID_SOLID_DEFENCE("invalidSolidDefence"),
    JOIN("join"),
    JOURNEYMEN("journeymen"),
    KEY_BINDINGS("keyBindings"),
    KICKOFF_RETURN("kickoffReturn"),
    KICK_SKILL("kickSkill"),
    LEAVE_GAME("leaveGame"),
    OPPONENT_BLOCK_SELECTION("opponentBlockSelection"),
    PASS_BLOCK("passBlock"),
    PETTY_CASH("pettyCash"),
    PILE_DRIVER("pileDriver"),
    PILING_ON("pilingOn"),
    PLAYER_CHOICE("playerChoice"),
    PROGRESS_BAR("progressBar"),
    RECEIVE_CHOICE("receiveChoice"),
    RE_ROLL("reRoll"),
    RE_ROLL_BLOCK_FOR_TARGETS("reRollBlockForTargets"),
    RE_ROLL_FOR_TARGETS("reRollForTargets"),
    SELECT_BLITZ_TARGET("selectBlitzTarget"),
    SELECT_GAZE_TARGET("selectGazeTarget"),
    SELECT_SKILL("selectSkill"),
    SELECT_WEATHER("selectWeather"),
    SETUP_ERROR("setupError"),
    SKILL_USE("skillUse"),
    SOUND_VOLUME("soundVolume"),
    START_GAME("startGame"),
    SWARMING("swarming"),
    SWARMING_ERROR("swarmingError"),
    TEAM_CHOICE("teamChoice"),
    TEAM_SETUP("teamSetup"),
    TOUCHBACK("touchback"),
    USE_APOTHECARIES("useApothecaries"),
    USE_APOTHECARY("useApothecary"),
    USE_CHAINSAW("useChainsaw"),
    USE_IGOR("useIgor"),
    USE_IGORS("useIgors"),
    USE_INDUCEMENT("useInducement"),
    USE_MORTUARY_ASSISTANT("useMortuaryAssistant"),
    USE_MORTUARY_ASSISTANTS("useMortuaryAssistants"),
    WINNINGS_RE_ROLL("winningsReRoll"),
    WIZARD_SPELL("wizardSpell"),
    YES_OR_NO_QUESTION("yesOrNoQuestion"),
}
