package com.jervisffb.engine.serialize

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * TODO Make sure this is generated by the notebook
 */
val commonSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.model.inducements.Spell::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.model.inducements.wizards.Zap::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.pathfinder.PathFinder::class) {
        subclass(com.jervisffb.engine.rules.common.pathfinder.StandardPathFinder::class)
    }
}
