package com.jervisffb.engine.rules.bb2025.serialize

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 *
 * BB2025 subclass registrations for polymorphic bases defined in
 * `rules.common.*`. Composed with [coreSerializerModule] and
 * [bb2020SerializerModule] at boot in [JervisSerialization].
 */
val bb2025SerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.rules.common.tables.ArgueTheCallTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025ArgueTheCallTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025CasualtyTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StuntyInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardKickOffEventTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025LastingInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardPrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.RangeRuler::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025RangeRuler::class)
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.rules.StandardBB2025Rules::class, com.jervisffb.engine.rules.StandardBB2025RulesSerializer)
    }
    polymorphic(com.jervisffb.engine.rules.common.skills.SkillSettings::class) {
        subclass(com.jervisffb.engine.rules.bb2025.BB2025SkillSettings::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.TeamActions::class) {
        subclass(com.jervisffb.engine.rules.bb2025.BB2025TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.WeatherTable::class) {
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardWeatherTable::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizards.Wizard::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.SportsWizard::class)
    }
}
