# This file contains icons not defined in FUMBBL's icons.ini, but icons we still want to load from the network
https\://cdn.fumbbl.com/i/686417.png=players/iconsets/TheBlackGobbo.png
https\://cdn.fumbbl.com/i/719444=players/iconsets/CaptainKarinaVonRiesz.png
https\://cdn.fumbbl.com/i/699702=players/iconsets/EstelleLaVeneaux.png
https\://cdn.fumbbl.com/i/695526=players/iconsets/IvarEriksson.png
https\://cdn.fumbbl.com/i/751135=players/iconsets/JeremiahKool.png
https\://cdn.fumbbl.com/i/686414.png=players/iconsets/Grombrindal.png
https\://cdn.fumbbl.com/i/695529.png=players/iconsets/SkrorgSnowpelt.png
https\://cdn.fumbbl.com/i/695531.png=players/iconsets/ThorssonStoutmead.png
https\://cdn.fumbbl.com/i/699700.png=players/iconsets/BoaKonssstriktr.png
https\://cdn.fumbbl.com/i/735010.png=players/iconsets/RodneyRoachbait.png
https\://cdn.fumbbl.com/i/735011.png=players/iconsets/RowanaForestfoot.png
https\://cdn.fumbbl.com/i/686415=players/portraits/Grombrindal.png
https\://cdn.fumbbl.com/i/686416=players/portraits/TheBlackGobbo.png
https\://cdn.fumbbl.com/i/695527=players/portraits/IvarEriksson.png
https\://cdn.fumbbl.com/i/695528=players/portraits/SkrorgSnowpelt.png
https\://cdn.fumbbl.com/i/695530=players/portraits/ThorssonStoutmead.png
https\://cdn.fumbbl.com/i/699699=players/portraits/BoaKonssstriktr.png
https\://cdn.fumbbl.com/i/699701=players/portraits/EstelleLaVeneaux.png
https\://cdn.fumbbl.com/i/719296=players/portraits/CaptainKarinaVonRiesz.png
https\://cdn.fumbbl.com/i/751134=players/portraits/JeremiahKool.png
https\://cdn.fumbbl.com/i/735021=players/portraits/RodneyRoachbait.png
https\://cdn.fumbbl.com/i/735022=players/portraits/RowanaForestfoot.png

