{
  "formatVersion": "1.1",
  "component": {
    "url": "../../external/main-SNAPSHOT/external-main-SNAPSHOT.module",
    "group": "com.juul.indexeddb",
    "module": "external",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "external-js.klib",
          "url": "external-js-main-SNAPSHOT.klib",
          "size": 40085,
          "sha512": "f99e078442a2fc174235ff9c94cd5f84aeff1e2029b02889166250e77bfdb845dcf21062ac6d86d42dbbc8bc9473773901c397a340b5b12de9d0cf73e3a6405f",
          "sha256": "859086508e6a724bfe36156aa0df9d4e7b2f9d031748c985c98742c2608313ba",
          "sha1": "db32403c61a4548da12a9507eda315af94eb6495",
          "md5": "81f4cf6641a85f9746cd46cad5f2ea03"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "external-js.klib",
          "url": "external-js-main-SNAPSHOT.klib",
          "size": 40085,
          "sha512": "f99e078442a2fc174235ff9c94cd5f84aeff1e2029b02889166250e77bfdb845dcf21062ac6d86d42dbbc8bc9473773901c397a340b5b12de9d0cf73e3a6405f",
          "sha256": "859086508e6a724bfe36156aa0df9d4e7b2f9d031748c985c98742c2608313ba",
          "sha1": "db32403c61a4548da12a9507eda315af94eb6495",
          "md5": "81f4cf6641a85f9746cd46cad5f2ea03"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "external-js-sources.jar",
          "url": "external-js-main-SNAPSHOT-sources.jar",
          "size": 12245,
          "sha512": "3a2a028c6d96e51dae7e0b02e11c504ff9298870bb44447ac26ef030879243e61b617c5cce1eea0ed755f5bb842e76d2d5165d836ae894d27cf2e6c4c56451c5",
          "sha256": "4544ba103a2fb3e00dddea0830aab9d643e95b71ab38b16911521fe08d0a90d7",
          "sha1": "2c02469ccb20ce1a4217a9b9fbaab27f4ed88140",
          "md5": "b192d9f78d0090893e39dd1af7468c30"
        }
      ]
    }
  ]
}
