package com.jervisffb.engine.model

enum class StadiumType {
    STANDARD,

    // Unusual Playing Surface
    ANKLE_DEEP_WATER,
    SLOPING_PITCH,
    ICE,
    ASTROGRANITE,
    UNEVEN_FOOTING,
    SOLID_STONE,

    // Rough & Ready Stadium
    APATHETIC_OFFICIALS,
    APPALLING_STANDS,
    UNCOVERED_TRAPDOORS,
    UNCLEAR_MARKINGS,
    DESPERATE_FOR_EXPOSURE,
    POORLY_BUILT_DUNGEONS,

    // Luxury Stadium
    INTEGRATED_MERCHANDISE_STALLS,
    REPUTATION_FOR_SPECTACLE,
    BROADCAST_STUDIO,
    ONSITE_APOTHECARIES,
    ENCLOSED_PITCH,
    DELUXE_SEATING,

    // Local Crowd
    ALE_FUELLED_MANIACS,
    BOISTEROUS_RABBIE,
    KNOW_IT_ALL_HECKLERS,
    BUNCH_OF_PACIFISTS,
    FICKLE_FANS,
    SOLEMN_AND_SILENT,
}
