package com.jervisffb.engine.common.serialization

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/** Generated by :tools:generateSerializers. DO NOT MODIFY! */
val commonSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.actions.InducementSelection::class) {
        subclass(com.jervisffb.engine.common.inducements.InducementSelectionCommon.BiasedReferee::class)
        subclass(com.jervisffb.engine.common.inducements.InducementSelectionCommon.InfamousCoach::class)
        subclass(com.jervisffb.engine.common.inducements.InducementSelectionCommon.Mercenary::class)
        subclass(com.jervisffb.engine.common.inducements.InducementSelectionCommon.Simple::class)
        subclass(com.jervisffb.engine.common.inducements.InducementSelectionCommon.StarPlayer::class)
        subclass(com.jervisffb.engine.common.inducements.InducementSelectionCommon.Wizard::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.InducementEffect::class) {
        subclass(com.jervisffb.engine.common.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.common.inducements.wizards.Zap::class)
        polymorphic(com.jervisffb.engine.model.inducements.wizard.Spell::class) {
            subclass(com.jervisffb.engine.common.inducements.wizards.Fireball::class)
            subclass(com.jervisffb.engine.common.inducements.wizards.Zap::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.Inducement::class) {
        subclass(com.jervisffb.engine.common.inducements.BiasedRefereeInducement::class)
        subclass(com.jervisffb.engine.common.inducements.BiasedRefereesInducementGroup::class)
        subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffInducement::class)
        subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffsInducementGroup::class)
        subclass(com.jervisffb.engine.common.inducements.MercenaryInducement::class)
        subclass(com.jervisffb.engine.common.inducements.SimpleInducement::class)
        subclass(com.jervisffb.engine.common.inducements.StandardMercenaryInducement::class)
        subclass(com.jervisffb.engine.common.inducements.StarPlayerInducement::class)
        subclass(com.jervisffb.engine.common.inducements.StarPlayersInducementGroup::class)
        subclass(com.jervisffb.engine.common.inducements.WizardInducement::class)
        subclass(com.jervisffb.engine.common.inducements.WizardsInducementGroup::class)
        polymorphic(com.jervisffb.engine.common.inducements.InducementGroupCommon::class) {
            subclass(com.jervisffb.engine.common.inducements.BiasedRefereesInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffsInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.StarPlayersInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.WizardsInducementGroup::class)
        }
        polymorphic(com.jervisffb.engine.model.inducements.settings.InducementGroup::class) {
            subclass(com.jervisffb.engine.common.inducements.BiasedRefereesInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffsInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.StarPlayersInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.WizardsInducementGroup::class)
            polymorphic(com.jervisffb.engine.common.inducements.InducementGroupCommon::class) {
                subclass(com.jervisffb.engine.common.inducements.BiasedRefereesInducementGroup::class)
                subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffsInducementGroup::class)
                subclass(com.jervisffb.engine.common.inducements.StarPlayersInducementGroup::class)
                subclass(com.jervisffb.engine.common.inducements.WizardsInducementGroup::class)
            }
        }
        polymorphic(com.jervisffb.engine.model.inducements.settings.SingleInducement::class) {
            subclass(com.jervisffb.engine.common.inducements.BiasedRefereeInducement::class)
            subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffInducement::class)
            subclass(com.jervisffb.engine.common.inducements.MercenaryInducement::class)
            subclass(com.jervisffb.engine.common.inducements.SimpleInducement::class)
            subclass(com.jervisffb.engine.common.inducements.StarPlayerInducement::class)
            subclass(com.jervisffb.engine.common.inducements.WizardInducement::class)
        }
        polymorphic(com.jervisffb.engine.model.inducements.settings.TeamPlayerInducement::class) {
            subclass(com.jervisffb.engine.common.inducements.StandardMercenaryInducement::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.InducementGroup::class) {
        subclass(com.jervisffb.engine.common.inducements.BiasedRefereesInducementGroup::class)
        subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffsInducementGroup::class)
        subclass(com.jervisffb.engine.common.inducements.StarPlayersInducementGroup::class)
        subclass(com.jervisffb.engine.common.inducements.WizardsInducementGroup::class)
        polymorphic(com.jervisffb.engine.common.inducements.InducementGroupCommon::class) {
            subclass(com.jervisffb.engine.common.inducements.BiasedRefereesInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffsInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.StarPlayersInducementGroup::class)
            subclass(com.jervisffb.engine.common.inducements.WizardsInducementGroup::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.InducementType::class) {
        subclass(com.jervisffb.engine.common.inducements.InducementTypeCommon::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.SingleInducement::class) {
        subclass(com.jervisffb.engine.common.inducements.BiasedRefereeInducement::class)
        subclass(com.jervisffb.engine.common.inducements.InfamousCoachingStaffInducement::class)
        subclass(com.jervisffb.engine.common.inducements.MercenaryInducement::class)
        subclass(com.jervisffb.engine.common.inducements.SimpleInducement::class)
        subclass(com.jervisffb.engine.common.inducements.StarPlayerInducement::class)
        subclass(com.jervisffb.engine.common.inducements.WizardInducement::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.TeamPlayerInducement::class) {
        subclass(com.jervisffb.engine.common.inducements.StandardMercenaryInducement::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizard.Spell::class) {
        subclass(com.jervisffb.engine.common.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.common.inducements.wizards.Zap::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.pathfinder.PathFinder::class) {
        subclass(com.jervisffb.engine.common.pathfinder.PathFinderCommon::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.planner.ActionPlanner::class) {
        subclass(com.jervisffb.engine.common.planner.ActionPlannerCommon::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.common.tables.DisabledCasualtyTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.common.tables.DisabledLastingInjuryTable::class)
    }
}
