package com.jervisffb.engine.common.serialization

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/** Generated by :tools:generateSerializers. DO NOT MODIFY! */
val commonSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.model.inducements.InducementEffect::class) {
        subclass(com.jervisffb.engine.common.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.common.inducements.wizards.Zap::class)
        polymorphic(com.jervisffb.engine.model.inducements.Spell::class) {
            subclass(com.jervisffb.engine.common.inducements.wizards.Fireball::class)
            subclass(com.jervisffb.engine.common.inducements.wizards.Zap::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.Spell::class) {
        subclass(com.jervisffb.engine.common.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.common.inducements.wizards.Zap::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.pathfinder.PathFinder::class) {
        subclass(com.jervisffb.engine.common.pathfinder.StandardPathFinder::class)
    }
}
