package com.jervisffb.engine.bb2025.serialization

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/** Generated by :tools:generateSerializers. DO NOT MODIFY! */
val bb2025SerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.common.AbstractRules::class) {
        subclass(com.jervisffb.engine.bb2025.StandardBB2025Rules::class, com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizards.Wizard::class) {
        subclass(com.jervisffb.engine.bb2025.inducements.wizards.SportsWizard::class)
        polymorphic(com.jervisffb.engine.bb2025.inducements.wizards.BB2025Wizard::class) {
            subclass(com.jervisffb.engine.bb2025.inducements.wizards.SportsWizard::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.bb2025.StandardBB2025Rules::class, com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer)
        polymorphic(com.jervisffb.engine.common.AbstractRules::class) {
            subclass(com.jervisffb.engine.bb2025.StandardBB2025Rules::class, com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer)
        }
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.TeamActions::class) {
        subclass(com.jervisffb.engine.bb2025.BB2025TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.skills.SkillSettings::class) {
        subclass(com.jervisffb.engine.bb2025.BB2025SkillSettings::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.ArgueTheCallTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025ArgueTheCallTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025CasualtyTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025StandardInjuryTable::class)
        subclass(com.jervisffb.engine.bb2025.tables.BB2025StuntyInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025StandardKickOffEventTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025LastingInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025StandardPrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.RangeRuler::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025RangeRuler::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.WeatherTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB2025StandardWeatherTable::class)
    }
}
