package com.jervisffb.engine.bb2025.serialization

import com.jervisffb.engine.bb2025.BB2025SkillSettings
import com.jervisffb.engine.bb2025.BB2025TeamActions
import com.jervisffb.engine.bb2025.StandardBB2025Rules
import com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer
import com.jervisffb.engine.bb2025.inducements.wizards.SportsWizard
import com.jervisffb.engine.bb2025.tables.BB2025ArgueTheCallTable
import com.jervisffb.engine.bb2025.tables.BB2025CasualtyTable
import com.jervisffb.engine.bb2025.tables.BB2025LastingInjuryTable
import com.jervisffb.engine.bb2025.tables.BB2025RangeRuler
import com.jervisffb.engine.bb2025.tables.BB2025StandardInjuryTable
import com.jervisffb.engine.bb2025.tables.BB2025StandardKickOffEventTable
import com.jervisffb.engine.bb2025.tables.BB2025StandardPrayersToNuffleTable
import com.jervisffb.engine.bb2025.tables.BB2025StandardWeatherTable
import com.jervisffb.engine.bb2025.tables.BB2025StuntyInjuryTable
import com.jervisffb.engine.model.inducements.wizards.Wizard
import com.jervisffb.engine.rules.Rules
import com.jervisffb.engine.rules.common.actions.TeamActions
import com.jervisffb.engine.rules.common.skills.SkillSettings
import com.jervisffb.engine.rules.common.tables.ArgueTheCallTable
import com.jervisffb.engine.rules.common.tables.CasualtyTable
import com.jervisffb.engine.rules.common.tables.InjuryTable
import com.jervisffb.engine.rules.common.tables.KickOffTable
import com.jervisffb.engine.rules.common.tables.LastingInjuryTable
import com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable
import com.jervisffb.engine.rules.common.tables.RangeRuler
import com.jervisffb.engine.rules.common.tables.WeatherTable
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 *
 * BB2025 subclass registrations for polymorphic bases defined in
 * `rules.common.*`. Composed with [coreSerializerModule] and
 * [bb2020SerializerModule] at boot in [JervisSerialization].
 */
val bb2025SerializerModule = SerializersModule {
    polymorphic(ArgueTheCallTable::class) {
        subclass(BB2025ArgueTheCallTable::class)
    }
    polymorphic(CasualtyTable::class) {
        subclass(BB2025CasualtyTable::class)
    }
    polymorphic(InjuryTable::class) {
        subclass(BB2025StandardInjuryTable::class)
        subclass(BB2025StuntyInjuryTable::class)
    }
    polymorphic(KickOffTable::class) {
        subclass(BB2025StandardKickOffEventTable::class)
    }
    polymorphic(LastingInjuryTable::class) {
        subclass(BB2025LastingInjuryTable::class)
    }
    polymorphic(PrayersToNuffleTable::class) {
        subclass(BB2025StandardPrayersToNuffleTable::class)
    }
    polymorphic(RangeRuler::class) {
        subclass(BB2025RangeRuler::class)
    }
    polymorphic(Rules::class) {
        subclass(StandardBB2025Rules::class, StandardBB2025RulesSerializer)
    }
    polymorphic(SkillSettings::class) {
        subclass(BB2025SkillSettings::class)
    }
    polymorphic(TeamActions::class) {
        subclass(BB2025TeamActions::class)
    }
    polymorphic(WeatherTable::class) {
        subclass(BB2025StandardWeatherTable::class)
    }
    polymorphic(Wizard::class) {
        subclass(SportsWizard::class)
    }
}
