package com.jervisffb.engine.bb2025.serialization

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/** Generated by :tools:generateSerializers. DO NOT MODIFY! */
val bb2025SerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.common.AbstractRules::class) {
        subclass(com.jervisffb.engine.bb2025.BB7Rules2025::class)
        subclass(com.jervisffb.engine.bb2025.StandardBB2025Rules::class, com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer)
    }
    polymorphic(com.jervisffb.engine.model.inducements.InducementEffect::class) {
        subclass(com.jervisffb.engine.bb2025.inducements.effects.DiscardedBananaSkin::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.GrudgeMatch::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.Hangover::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.MagicScroll::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.RazzleDazzle::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.SetPiece::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.SportsEspionage::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.YouDope::class)
        polymorphic(com.jervisffb.engine.bb2025.inducements.effects.DesperateMeasures::class) {
            subclass(com.jervisffb.engine.bb2025.inducements.effects.DiscardedBananaSkin::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.GrudgeMatch::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.Hangover::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.MagicScroll::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.RazzleDazzle::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.SetPiece::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.SportsEspionage::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.YouDope::class)
        }
        polymorphic(com.jervisffb.engine.model.inducements.card.SpecialPlayCard::class) {
            subclass(com.jervisffb.engine.bb2025.inducements.effects.DiscardedBananaSkin::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.GrudgeMatch::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.Hangover::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.MagicScroll::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.RazzleDazzle::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.SetPiece::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.SportsEspionage::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.YouDope::class)
            polymorphic(com.jervisffb.engine.bb2025.inducements.effects.DesperateMeasures::class) {
                subclass(com.jervisffb.engine.bb2025.inducements.effects.DiscardedBananaSkin::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.GrudgeMatch::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.Hangover::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.MagicScroll::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.RazzleDazzle::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.SetPiece::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.SportsEspionage::class)
                subclass(com.jervisffb.engine.bb2025.inducements.effects.YouDope::class)
            }
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.biasedreferee.BiasedReferee::class) {
        subclass(com.jervisffb.engine.bb2025.inducements.biasedreferee.DodgyLeagueRep::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.card.SpecialPlayCard::class) {
        subclass(com.jervisffb.engine.bb2025.inducements.effects.DiscardedBananaSkin::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.GrudgeMatch::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.Hangover::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.MagicScroll::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.RazzleDazzle::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.SetPiece::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.SportsEspionage::class)
        subclass(com.jervisffb.engine.bb2025.inducements.effects.YouDope::class)
        polymorphic(com.jervisffb.engine.bb2025.inducements.effects.DesperateMeasures::class) {
            subclass(com.jervisffb.engine.bb2025.inducements.effects.DiscardedBananaSkin::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.GrudgeMatch::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.Hangover::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.MagicScroll::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.RazzleDazzle::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.SetPiece::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.SportsEspionage::class)
            subclass(com.jervisffb.engine.bb2025.inducements.effects.YouDope::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.settings.InducementType::class) {
        subclass(com.jervisffb.engine.bb2025.inducements.InducementType2025::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizard.Wizard::class) {
        subclass(com.jervisffb.engine.bb2025.inducements.wizards.SportsWizard::class)
        polymorphic(com.jervisffb.engine.bb2025.inducements.wizards.Wizard2025::class) {
            subclass(com.jervisffb.engine.bb2025.inducements.wizards.SportsWizard::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.bb2025.BB7Rules2025::class)
        subclass(com.jervisffb.engine.bb2025.StandardBB2025Rules::class, com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer)
        polymorphic(com.jervisffb.engine.common.AbstractRules::class) {
            subclass(com.jervisffb.engine.bb2025.BB7Rules2025::class)
            subclass(com.jervisffb.engine.bb2025.StandardBB2025Rules::class, com.jervisffb.engine.bb2025.StandardBB2025RulesSerializer)
        }
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.TeamActions::class) {
        subclass(com.jervisffb.engine.bb2025.TeamActions2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.skills.SkillSettings::class) {
        subclass(com.jervisffb.engine.bb2025.SkillSettings2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.ArgueTheCallTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.ArgueTheCallTable2025::class)
        subclass(com.jervisffb.engine.bb2025.tables.BB7ArgueTheCallTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.CasualtyTable2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.DesperateMeasuresTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB7DesperateMeasuresTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB7StandardInjuryTable::class)
        subclass(com.jervisffb.engine.bb2025.tables.BB7StuntyInjuryTable::class)
        subclass(com.jervisffb.engine.bb2025.tables.StandardInjuryTable2025::class)
        subclass(com.jervisffb.engine.bb2025.tables.StuntyInjuryTable2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB7KickOffEventTable::class)
        subclass(com.jervisffb.engine.bb2025.tables.StandardKickOffEventTable2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.LastingInjuryTable2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.BB7PrayersToNuffleTable::class)
        subclass(com.jervisffb.engine.bb2025.tables.StandardPrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.RangeRuler::class) {
        subclass(com.jervisffb.engine.bb2025.tables.RangeRuler2025::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.WeatherTable::class) {
        subclass(com.jervisffb.engine.bb2025.tables.StandardWeatherTable2025::class)
    }
}
